### ISSUE TITLE
Looks like Dora can't handle spaces in folders

### ISSUE THREAD

**Issue by markleusink** [camac/dora#12]
My account name on Windows 7 (x64) is "Mark Leusink", so my home folder is c:\Users\Mark Leusink

Here's the error I'm getting after installing Dora and trying my first stage:

![capture](https://f.cloud.github.com/assets/1773707/805084/6ca5a802-ee20-11e2-985e-9344f74941e4.JPG)

**Comment by camac** [comment]
Hi Mark thanks for the Bug Report, this is exactly the sort of issues I am trying to collect with this beta release!

I will work on a permanent fix for this tonight/tomorrow night, but probably not until tomorrow night as [State Of Origin](https://en.wikipedia.org/wiki/State_of_Origin_series) game 3 is on tonight... :)

If you want to get dora working in the meantime, i just pushed a branch hotfix/nospaces with just makes 2 small changes to the install and repo setup to instead use c:\xsltproc as the location for xsltproc 
if you checkout this branch and re-install and re-configure repo it should work ok.

alternatively you could add your  `C:\Users\Mark Leusink\bin` directory to your windows PATH environment variable, and then edit the git config file (in sourcetree Settings and then edit config) and change
`c:/Users/Mark Leusink/bin/xsltproc xsl/DXLClean -`
to just 
`xsltproc xsl/DXLClean -`
and likewise for smudge filter
and sourcetree should then be able to run xsltproc due to it being on the PATH

My intention with the install process was to try and keep it all in the HOME directory in case anyone has user restrictions, and also try to avoid having to edit the path variable... so hopefully I can come up with a solution that fits this criteria

**Comment by markleusink** [comment]
With the fix you've added it now seems to work!
