### ISSUE TITLE
Uninstall leaves [filter] section in git config file

### ISSUE THREAD

**Issue by markleusink** [camac/dora#14]
Did a uninstall on a repo. The script left the [filter "dxlmetadata"] section header in the git config file.

After a re-install, I now have 2 headers in that file. Not sure if that matters though.

![capture](https://f.cloud.github.com/assets/1773707/810604/1008fd38-eebb-11e2-9e08-7e5cee7138d5.JPG)

**Comment by camac** [comment]
Hi Mark, thanks again for this bug. I would prefer to fix this as I don't want to leave a mess behind on uninstallation.

I thought I had used `git config --remove-section filter.dxlmetadata` but in fact I was still using `git config --unset filter.dxlmetadata.clean` etc.

I am going to update the filter uninstallation to use the `--remove-section` option, because this will correctly remove the section.

I'll include this with the next release v0.1.1

Cameron

**Comment by markleusink** [comment]
You might also want to check if after an uninstall the /bin and /dora folders are empty and remove them if they are. Looks like the uninstall script doesn't do that.

**Comment by camac** [comment]
Thanks Mark, I will include this in v0.1.1 should be simple enough to do
