### ISSUE TITLE
Describe how Dora works

### ISSUE THREAD

**Issue by markleusink** [camac/dora#15]
I understand in general what Dora does, but I think it would be useful to write some additional documentation on how the filter process actually works (maybe with diagrams like the ones here: http://git-scm.com/book/ch7-2.html). This will make it less scary to start using Dora :-)

I'm also curious as to what happens if you import filtered design elements from a repo into a (new) database. Since it doesn't have some of the fields in the DXL, does Designer automatically complete that? Or does it throw an error?

**Comment by camac** [comment]
Yes I know what you mean. The thought that something is modifying your design element on your behalf is a little unsettling....
I totally agree on the additional documentation front. My intention was to actually record another video of how Dora works, which would focus on the actual mechanism within git, and then also the XSLT part. Then also either some more videos or documentation on the questions like you've asked such as 
- what happens if you totally build an NSF from the Filtered DXL, 
- how to you convert an existing nsf repository to a filtered repository 
- what considerations need to be (with considerations to perhaps multi-developer situations) 
- how would you 'upgrade' the version of the xsl file you are using, and what would you need to do
- what considerations would you need before deployment of a freshly built  NSF from a filtered repo
- and more....

To give you an idea of my rough order of attacking this. First my priority was to get the Beta release to allow anyone interested to raise these sorts of bugs and practical questions, and also I hope to get some feedback from anyone who has expert knowledge on DXL. 
Then I did the 'Intro' video because it was hard to explain in words why anyone might be interested, and this video was mainly to get people interested in beta testing.
Next I want to fix the bugs and address concerns that come out of the beta testing, and develop the documentation so a team could read, understand and get started working together with it.
Version 1.0.0 of Dora will be the release that I would say this should be ready to use in a team environment, on real NSF's. 

What I have learned and understood about DXL has been mainly from the: 
- Domino Designer help file on Domino DTD
- hands-on experience
- 1 blog post that I can't remember where it is : ) 
- Andre Guirard did a very helpful article on the [Domino Developer Wiki](http://www-10.lotus.com/ldd/ddwiki.nsf/dx/ls-design-programming.htm?OpenDocument&sa=true) 

To try and give a quick answer to what happens if you import the filtered design elements from a repo into a new database. Yes, designer will fill in the blanks. Imagine an attribute like replicaID will be already set at database level, and would be overwritten anyway. Noteinfo will be created because of a new note being created. 
If you look through the Domino DTD in designer help, the attributes and elements that are **implied** are optional.
The only DXL error I have seen so far, is a DXL.Parse error for the `<background>` element, when I had not un-indented the dxl. It did not like the extra whitespace between elements for that particular element. So this is why I 'un-indent' on checkout.
There are some fields that Dora strips out like the object fields $something_O and the $$ScriptName fields that will not appear until the element is recompiled. 
Also I believe the elements need to be signed but I believe this may be true for any imported DXL, filtered or not.
For an Design Element that is already in your nsf, and you check out a filtered version of that element. I _believe_ of the top of my head, that after import it will use the same _note_ and it will have the same updated/modified signed details, but just have updated the DXL. But I will need to double check this, and I agree it would be much more comforting to see some of these demonstrated in a video or documented.
